### ISSUE TITLE
Update to "silverstripe/framework": "^3.1.0"

### ISSUE THREAD

**Issue by banglashi** [nglasl/silverstripe-misdirection#12]
Hi @nglasl 
great package! Would it be possible to update the dependency from "silverstripe/framework": "3.1.*" to "silverstripe/framework": "^3.1.0"? We are using 3.2.* and used a fork to try it out, seems to work all fine.
Thanks

**Comment by nglasl** [comment]
Sorry for the delayed response. I'm planning on going through and doing a proper 3.2 update very soon (replacing anything that changed fundamentally come 4.0), rather than just bumping the dependency :)

I will however keep you in the loop, so you don't need to maintain a fork. Thanks for letting me know!

**Comment by banglashi** [comment]
Cool. Thanks. Should I keep the issue open until then or close it?

**Comment by nglasl** [comment]
We'll leave it open for now, just as a reminder :)

**Comment by nglasl** [comment]
I just wanted to let you know that **2.2.0** has been released, which bumps the framework dependency to 3.2 as you were looking for. I haven't found time to look any further into the update, so please keep in mind that some things *may* not play nicely until then :)

**Comment by banglashi** [comment]
Thanks!
