### ISSUE TITLE
Handle codepath when calling $this->httpError()

### ISSUE THREAD

**Issue by SilbinaryWolf** [nglasl/silverstripe-misdirection#16]
This module needs to handle cases where $this->httpError() has been called which essentially throws 
`throw new SS_HTTPResponse_Exception($errorMessage, $errorCode);` causing the codepath to be hoisted and never call 'MisdirectionRequestFilter::postRequest'.

I made this PR https://github.com/nglasl/silverstripe-misdirection/pull/14 but it doesn't handle other cases of the module, so it's not ideal and this problem needs to be thought about a bit more.

**Comment by nglasl** [comment]
Coming back to this, just so others viewing the issue are aware.. When a `httpError(404)` has been thrown, it will still indeed hook into the post request filter as expected. The module however was having trouble determining the appropriate fallback (since it was expecting to find a URL segment that did not exist). The logic behind this has now been improved, and this should no longer be an issue.
