### ISSUE TITLE
working locally (mamp), but not working on live site

### ISSUE THREAD

**Issue by guyvanbael** [nglasl/silverstripe-misdirection#22]
for a client i prepared this locally and deployed it. When i test the mapping on my mamp stack. Everything works.Testing the mapping on live site is ok. But when i paste the link in my browser, i get a 404 .Can someone help me with this?
![cisa1](https://cloud.githubusercontent.com/assets/3098809/24243786/94e4c476-0fbc-11e7-95cb-5610998adcc8.png)
![cisa2](https://cloud.githubusercontent.com/assets/3098809/24243787/94e63108-0fbc-11e7-82f5-aa98f1263a87.png)
![cisa3](https://cloud.githubusercontent.com/assets/3098809/24243788/94e6183a-0fbc-11e7-81f1-83f29359b422.png)

**Comment by nglasl** [comment]
What happens when you use the testing interface on the live site? Also, does your mapping have "includes hostname"  checked? If not, it may be thinking that this should be a relative URL, as in "www.cisanet.be/www.cisanet.be/partners.php". Also while we're on the topic, do these mappings need to be absolute? Could they just be "partners.php"? That should work, assuming you're not trying to apply a mapping specifically for this one hostname.

**Comment by guyvanbael** [comment]
Hi Nathan,
Changing the path to a relative one (in this case partners.php) solves the problem. I didn't include hostname before. Thanks a lot for pointing this out!
Grrtz,
Guy
