### ISSUE TITLE
Doesn't work for URL ending with .php

### ISSUE THREAD

**Issue by mrvickiee** [nglasl/silverstripe-misdirection#27]
Is there any way to make the module to work with URL ending with .php?
Eg. www.example.com/a1.php

**Comment by nglasl** [comment]
Thanks for getting in touch. Did you have a specific example of what you're trying to do?

**Comment by mrvickiee** [comment]
Hi nglasl,

I created a Silverstripe website that replaces two old websites. So, the link from the old website that points to this new server must be redirected to corresponding page. Therefore, I am setting up 301 redirects. Example:
Link Type Simple
Mapped Link: test/test-redirection.php
Redirect Link: testnew/abc
Response Code 301
Priority 1

After setting up, going to mynewwebsite.com/test/test-redirection.php returns a 404 error.

**Comment by nglasl** [comment]
Apologies for the delayed response. I just ran up a test and your above example works perfectly for me.

When you say that it's returning a 404, is it staying on the same URL, or is it redirecting to the new URL but still returning a 404? Mine redirects to the new URL and then 404s, since I don't actually have a page set up on this URL.

**Comment by nglasl** [comment]
@mrvickiee, how'd you go with this?

**Comment by mrvickiee** [comment]
I commented "RewriteCond %{REQUEST_URI} !\.php$" in the .htaccess as a workaround.

**Comment by nglasl** [comment]
That might explain what's going on. Sounds like your `.htaccess` is not letting you hit Misdirection. I'm going to close this now that you've resolved the issue, but please let me know if you believe this goes deeper and requires further investigation.
