### ISSUE TITLE
SilverStripe 4.1 Support?

### ISSUE THREAD

**Issue by christopher-s** [nglasl/silverstripe-misdirection#28]
@nglasl Hey there - is the latest "dev-master' good with SilverStripe 4.1? Or stuck at 4.0?

**Comment by nglasl** [comment]
Hey @christopher-s. The latest dev-master is confirmed good with 4.1, thanks to semantic versioning on SS core. Though, I did notice that a unit test was failing in 4.1 due to https://github.com/silverstripe/silverstripe-versioned/issues/153. This doesn't cause any issues outside the unit test however.
